import { glob, readFile, writeFile } from 'node:fs/promises';
import { join, relative } from 'node:path';
import { format, resolveConfig } from 'prettier';
import { repoRoot } from '../lib/repo';

const DEMO_FILES = 'packages/features/*/demo/*.ts';
const SEED_FILES = 'packages/features/*/seed/*.seed.ts';

const HEADER = [
  '// Generated by `pnpm gen:feature`, and by `pnpm demo:registry` on demand. Do not edit.',
  '// `apps/api` bundles `demo` into one CJS file (`apps/api/tsup.config.ts`), which cannot resolve',
  "// this feature's own `demo/*.ts`/`seed/*.seed.ts` files if they are `import()`ed off disk at",
  '// runtime (ADR 0010) — importing them here, statically, lets `tsup` resolve them at build time.',
  "// A feature's `index.ts` imports this file for exactly that reason (ADR 0002 forbids anyone",
  "// else from reaching in here directly): registering this feature's own scenarios and resets is",
  "// this feature's own concern, not `demo`'s.",
];

/** Every `demo/*.ts` and `seed/*.seed.ts` file, grouped by the feature directory that owns it. */
const filesByFeature = async (root: string): Promise<Map<string, string[]>> => {
  const entries: string[] = [];
  for (const pattern of [DEMO_FILES, SEED_FILES]) {
    for await (const entry of glob(pattern, { cwd: root })) entries.push(entry);
  }

  const byFeature = new Map<string, string[]>();
  for (const entry of entries.sort((left, right) => left.localeCompare(right))) {
    const feature = entry.split('/')[2];
    if (feature === undefined) continue;
    byFeature.set(feature, [...(byFeature.get(feature) ?? []), entry]);
  }
  return byFeature;
};

const renderRegistry = (feature: string, files: readonly string[]): string =>
  [
    ...HEADER,
    '',
    ...files.map(
      (file) => `import './${relative(`packages/features/${feature}`, file).replace(/\.ts$/, '')}';`,
    ),
    '',
  ].join('\n');

/**
 * One generated file per feature, not one shared barrel in `apps/api`: `apps/api` may only import a
 * feature's `index.ts` (ADR 0002/0017), never `packages/features/<f>/demo/<file>.ts` directly, so a
 * cross-feature barrel living outside every feature could never legally name these files itself.
 */
export const composeDemoRegistries = async (root: string = repoRoot()): Promise<readonly string[]> => {
  const byFeature = await filesByFeature(root);
  const written: string[] = [];

  for (const [feature, files] of byFeature) {
    const target = join(root, 'packages/features', feature, 'registry.generated.ts');
    const options = await resolveConfig(target);
    const contents = await format(renderRegistry(feature, files), { ...options, filepath: target });
    const current = await readFile(target, 'utf8').catch(() => '');
    if (current !== contents) await writeFile(target, contents, 'utf8');
    written.push(target);
  }
  return written;
};
