export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'scope-enum': [
      2,
      'always',
      [
        'kernel',
        'shared',
        'db',
        'web',
        'api',
        'workers',
        'mcp',
        'adr',
        'tooling',
        'ci',
        'deps',
        'svj',
        'invoices',
        'payments',
        'receivables',
        'accounting-sync',
        'owners',
        'cadastre',
        'documents',
        'knowledge',
        'inspections',
        'defects',
        'tasks',
        'quotes',
        'field-reports',
        'fleet',
        'comms',
        'assemblies',
        'dunning',
        'reports',
        'copilot',
        'agent-builder',
        'api-tokens',
      ],
    ],
    'subject-case': [2, 'always', 'lower-case'],
  },
};
