import { glob, readFile, writeFile } from 'node:fs/promises';
import { basename, dirname } from 'node:path';
import { composedSchemaFile, repoRoot } from './paths';

const FEATURE_SCHEMAS = 'packages/features/*/schema.ts';
const KERNEL_SCHEMA = '../../kernel/src/db/schema/index';

const HEADER = [
  '// Generated by `pnpm db:generate`. Do not edit — add tables to a feature schema instead.',
  '// Drizzle Kit reads this module, so a table only exists for migrations once it is listed here.',
];

/** Sorted, so the committed file is the same on every machine and a diff means a real change. */
export const featureSchemaFiles = async (): Promise<readonly string[]> => {
  const found: string[] = [];
  for await (const entry of glob(FEATURE_SCHEMAS, { cwd: repoRoot() })) {
    found.push(entry);
  }
  return found.sort((left, right) => left.localeCompare(right));
};

const featureName = (entry: string): string => basename(dirname(entry));

export const renderComposedSchema = (features: readonly string[]): string =>
  [
    ...HEADER,
    '',
    `export * from '${KERNEL_SCHEMA}';`,
    ...features.map((entry) => `export * from '../../features/${featureName(entry)}/schema';`),
    '',
  ].join('\n');

/** Returns the rendered module, so the caller can compare it with what is on disk. */
export const composeSchema = async (): Promise<string> => {
  const contents = renderComposedSchema(await featureSchemaFiles());
  const target = composedSchemaFile();
  const current = await readFile(target, 'utf8').catch(() => '');
  if (current !== contents) await writeFile(target, contents, 'utf8');
  return contents;
};
