// Generated by `pnpm db:generate`. Do not edit — add tables to a feature schema instead.
// Drizzle Kit reads this module, so a table only exists for migrations once it is listed here.

export * from '../../kernel/src/db/schema/index';
