import { glob, readFile, writeFile } from 'node:fs/promises';
import { basename, dirname } from 'node:path';
import { format, resolveConfig } from 'prettier';
import { modulesFile, repoRoot } from './paths';

const FEATURE_MODULES = 'packages/features/*/api/*.module.ts';

const HEADER = [
  '// Generated by `pnpm gen:feature`, and by `pnpm api:modules` on demand. Do not edit.',
  '// Nest needs its modules statically: a glob would survive `tsx` in dev and vanish in the bundle.',
];

const pascal = (kebab: string): string =>
  kebab
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');

/** Sorted, so the composed file is the same on every machine and a diff means a real change. */
export const featureModuleFiles = async (root: string = repoRoot()): Promise<readonly string[]> => {
  const found: string[] = [];
  for await (const entry of glob(FEATURE_MODULES, { cwd: root })) {
    found.push(entry);
  }
  return found.sort((left, right) => left.localeCompare(right));
};

interface Discovered {
  readonly feature: string;
  readonly className: string;
}

/**
 * Discovery is by file name, the import is from the feature's `index.ts`. Reaching into
 * `api/…module.ts` directly would be an import from a feature's insides (ADR 0002), so the
 * convention has to hold on both ends: `svj/api/svj.module.ts` is exported as `SvjModule`.
 */
export const describeModule = (entry: string): Discovered => ({
  feature: basename(dirname(dirname(entry))),
  className: `${pascal(basename(entry).replace('.module.ts', ''))}Module`,
});

export const renderModules = (entries: readonly string[]): string => {
  const found = entries.map(describeModule);

  return [
    ...HEADER,
    '',
    "import type { Type } from '@nestjs/common';",
    ...found.map((it) => `import { ${it.className} } from '../../../../packages/features/${it.feature}';`),
    '',
    `export const featureModules: readonly Type[] = [${found.map((it) => it.className).join(', ')}];`,
    '',
  ].join('\n');
};

/**
 * Formatted with the repository's own Prettier config, because the list of modules is one array
 * literal that grows: at some number of features Prettier would want to wrap it, and a file whose
 * committed form disagrees with `pnpm lint` is a trap laid for whoever adds that feature.
 */
export const composedSource = async (root: string = repoRoot()): Promise<string> => {
  const target = modulesFile(root);
  const options = await resolveConfig(target);
  return format(renderModules(await featureModuleFiles(root)), { ...options, filepath: target });
};

/** Returns the composed module, so the caller can compare it with what is on disk. */
export const composeModules = async (root: string = repoRoot()): Promise<string> => {
  const contents = await composedSource(root);
  const target = modulesFile(root);
  const current = await readFile(target, 'utf8').catch(() => '');
  if (current !== contents) await writeFile(target, contents, 'utf8');
  return contents;
};
