// Generated by `pnpm api:modules`. Do not edit — add a feature with an api/*.module.ts instead.
// Nest needs its modules statically: a glob would survive `tsx` in dev and vanish in the bundle.

import type { Type } from '@nestjs/common';

export const featureModules: readonly Type[] = [];
