// Generated by `pnpm gen:feature`, and by `pnpm api:modules` on demand. Do not edit.
// Nest needs its modules statically: a glob would survive `tsx` in dev and vanish in the bundle.

import type { Type } from '@nestjs/common';

export const featureModules: readonly Type[] = [];
