import { glob, readFile, writeFile } from 'node:fs/promises';
import { basename, dirname } from 'node:path';
import { format, resolveConfig } from 'prettier';
import { navigationFile, repoRoot } from './paths';

const FEATURE_NAVIGATION = 'packages/features/*/ui/navigation.ts';

const HEADER = [
  '// Generated by `pnpm web:navigation`. Do not edit.',
  '// Next needs the list statically: a glob would survive `next dev` and vanish in the build.',
];

const camel = (kebab: string): string =>
  kebab
    .split('-')
    .map((part, index) => (index === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)))
    .join('');

/** Sorted, so the composed file is the same on every machine and a diff means a real change. */
export const featureNavigationFiles = async (root: string = repoRoot()): Promise<readonly string[]> => {
  const found: string[] = [];
  for await (const entry of glob(FEATURE_NAVIGATION, { cwd: root })) {
    found.push(entry);
  }
  return found.sort((left, right) => left.localeCompare(right));
};

/**
 * Discovery is by file name, the import is from the feature's `ui/index.ts` — the browser-facing
 * front door (ADR 0017). The root `index.ts` is the server side and pulls Nest in with it, which a
 * Next build cannot follow; `ui/navigation.ts` itself is the feature's insides and stays private.
 */
export const describeNavigation = (entry: string): string => basename(dirname(dirname(entry)));

export const renderNavigation = (entries: readonly string[]): string => {
  const features = entries.map(describeNavigation);
  const binding = (feature: string): string => `${camel(feature)}Navigation`;

  return [
    ...HEADER,
    '',
    "import type { NavigationItem } from '../../../../packages/shared/src/ui/navigation';",
    ...features.map(
      (it) => `import { navigation as ${binding(it)} } from '../../../../packages/features/${it}/ui/index';`,
    ),
    '',
    `export const featureNavigation: readonly NavigationItem[] = [${features
      .map((it) => `...${binding(it)}`)
      .join(', ')}];`,
    '',
  ].join('\n');
};

/** Formatted with the repository's own Prettier config; see `apps/api/src/features/compose.ts`. */
export const composedSource = async (root: string = repoRoot()): Promise<string> => {
  const target = navigationFile(root);
  const options = await resolveConfig(target);
  return format(renderNavigation(await featureNavigationFiles(root)), { ...options, filepath: target });
};

/** Returns the composed module, so the caller can compare it with what is on disk. */
export const composeNavigation = async (root: string = repoRoot()): Promise<string> => {
  const contents = await composedSource(root);
  const target = navigationFile(root);
  const current = await readFile(target, 'utf8').catch(() => '');
  if (current !== contents) await writeFile(target, contents, 'utf8');
  return contents;
};
