// Generated by `pnpm web:navigation`. Do not edit.
// Next needs the list statically: a glob would survive `next dev` and vanish in the build.

import type { NavigationItem } from '../../../../packages/shared/src/ui/navigation';

export const featureNavigation: readonly NavigationItem[] = [];
