// Generated by `pnpm gen:feature`, and by `pnpm demo:registry` on demand. Do not edit.
// `apps/api` bundles `demo` into one CJS file (`apps/api/tsup.config.ts`), which cannot resolve
// this feature's own `demo/*.ts`/`seed/*.seed.ts` files if they are `import()`ed off disk at
// runtime (ADR 0010) — importing them here, statically, lets `tsup` resolve them at build time.
// A feature's `index.ts` imports this file for exactly that reason (ADR 0002 forbids anyone
// else from reaching in here directly): registering this feature's own scenarios and resets is
// this feature's own concern, not `demo`'s.

import './demo/reset';
