import { readFile, writeFile } from 'node:fs/promises';
import { basename, dirname } from 'node:path';
import { format, resolveConfig } from 'prettier';
import { featureFilesMatching } from '../navigation/compose';
import { evidenceFile, repoRoot } from '../navigation/paths';

const FEATURE_EVIDENCE = 'packages/features/*/ui/evidence.ts';

const HEADER = [
  '// Generated by `pnpm web:navigation`. Do not edit.',
  '// Next needs the list statically: a glob would survive `next dev` and vanish in the build.',
];

const camel = (kebab: string): string =>
  kebab
    .split('-')
    .map((part, index) => (index === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)))
    .join('');

export const featureEvidenceFiles = (root: string = repoRoot()): Promise<readonly string[]> =>
  featureFilesMatching(FEATURE_EVIDENCE, root);

const featureOf = (entry: string): string => basename(dirname(dirname(entry)));

/**
 * How each feature's own proposals are shown in the approval inbox, keyed by tool name. Discovery
 * is by file name and the import is from the feature's `ui/index.ts` — the browser-facing front
 * door (ADR 0017), the same rule the navigation barrel follows.
 */
export const renderEvidence = (entries: readonly string[]): string => {
  const features = entries.map(featureOf);
  const binding = (feature: string): string => `${camel(feature)}Evidence`;

  return [
    ...HEADER,
    '',
    "import type { ComponentType } from 'react';",
    ...features.map(
      (it) =>
        `import { approvalEvidenceRenderers as ${binding(it)} } from '../../../../packages/features/${it}/ui/index';`,
    ),
    '',
    'export interface EvidenceRendererProps {',
    '  readonly input: unknown;',
    '}',
    '',
    'export const evidenceRenderers: Readonly<Record<string, ComponentType<EvidenceRendererProps>>> = {',
    ...features.map((it) => `  ...${binding(it)},`),
    '};',
    '',
  ].join('\n');
};

/** Formatted with the repository's own Prettier config; see `navigation/compose.ts`. */
export const composedEvidence = async (root: string = repoRoot()): Promise<string> => {
  const target = evidenceFile(root);
  const options = await resolveConfig(target);
  return format(renderEvidence(await featureEvidenceFiles(root)), { ...options, filepath: target });
};

export const composeEvidence = async (root: string = repoRoot()): Promise<string> => {
  const contents = await composedEvidence(root);
  const target = evidenceFile(root);
  const current = await readFile(target, 'utf8').catch(() => '');
  if (current !== contents) await writeFile(target, contents, 'utf8');
  return contents;
};
