// Generated by `pnpm web:navigation`. Do not edit.
// Next needs the list statically: a glob would survive `next dev` and vanish in the build.

import type { ComponentType } from 'react';
import { approvalEvidenceRenderers as invoicesEvidence } from '../../../../packages/features/invoices/ui/index';
import { approvalEvidenceRenderers as paymentsEvidence } from '../../../../packages/features/payments/ui/index';

export interface EvidenceRendererProps {
  readonly input: unknown;
}

export const evidenceRenderers: Readonly<Record<string, ComponentType<EvidenceRendererProps>>> = {
  ...invoicesEvidence,
  ...paymentsEvidence,
};
